/**
 * Liam, one file per beat, at the take the operator chose.
 *
 *   node scripts/ad-vo.mjs --dry-run
 *   node scripts/ad-vo.mjs
 *
 * Rendered through /with-timestamps so each take arrives with its own
 * character alignment. That buys two things at no extra cost: exact caption
 * timings whenever captions are wanted, and a real measurement of how much of
 * each beat is speech and how much is air — which is what the edit has to
 * budget around.
 *
 * Beat 10 has no line. It is the promo card's three seconds and a sound punch;
 * narration over it would be talking across the only moment the film asks the
 * viewer to just look.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { AD, SPOKEN, VOICE, BUDGET_SECONDS } from "../src/ad-script.js";
import { logCall, STAGING } from "./spend-log.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SITE_ROOT = path.resolve(HERE, "..", "..");
const VO_DIR = path.join(STAGING, "ad-vo");
const OUT = path.resolve(HERE, "..", "src", "ad-timings.json");
const MODEL = "eleven_multilingual_v2";
const PAUSE_FLOOR = 0.09;

function loadKey() {
  for (const file of [".env.local", ".env"]) {
    const p = path.join(SITE_ROOT, file);
    if (!fs.existsSync(p)) continue;
    const m = fs.readFileSync(p, "utf8")
      .match(/^\s*ELEVENLABS_API_KEY\s*=\s*(.+?)\s*$/m);
    if (m) return m[1].replace(/^["']|["']$/g, "");
  }
  return null;
}

function pauseSeconds(align) {
  const { characters, character_start_times_seconds: s,
          character_end_times_seconds: e } = align;
  let total = 0;
  for (let i = 0; i < characters.length; i++) {
    const dur = e[i] - s[i];
    if (/[\s.,;:!?…—-]/.test(characters[i]) && dur > PAUSE_FLOOR) {
      total += dur - PAUSE_FLOOR;
    }
  }
  return total;
}

async function main() {
  const args = process.argv.slice(2);
  const chars = SPOKEN.reduce((t, b) => t + b.line.length, 0);
  console.log(`${SPOKEN.length} spoken beats of ${AD.length} · ${chars} credits`);
  console.log(`picture budget from the brief: ${BUDGET_SECONDS.toFixed(1)}s\n`);
  if (args.includes("--dry-run")) {
    console.log("--dry-run: nothing sent, nothing spent.");
    return;
  }

  const key = loadKey();
  if (!key) { console.error("ELEVENLABS_API_KEY not found."); process.exit(2); }
  fs.mkdirSync(VO_DIR, { recursive: true });

  const beats = [];
  console.log("beat  budget  vo      pause   line");
  console.log("─".repeat(72));

  for (const b of AD) {
    const id = `ad${String(b.n).padStart(2, "0")}`;
    if (!b.line.trim()) {
      beats.push({ ...b, id, vo: 0, pause: 0, captions: [] });
      console.log(`${String(b.n).padStart(4)}  ${b.seconds.toFixed(1)}s    —       —       (silent — picture only)`);
      continue;
    }

    const res = await fetch(
      `https://api.elevenlabs.io/v1/text-to-speech/${VOICE.id}/with-timestamps` +
      "?output_format=mp3_44100_128",
      { method: "POST",
        headers: { "xi-api-key": key, "Content-Type": "application/json" },
        body: JSON.stringify({ text: b.line, model_id: MODEL,
                               voice_settings: VOICE.settings }) });

    if (!res.ok) {
      console.log(`${id}: FAILED ${res.status} ${(await res.text()).slice(0, 140)}`);
      logCall({ provider: "elevenlabs", model: MODEL, unit: "characters",
                quantity: 0, usd: 0, exact: true, output: null,
                note: `${id}: HTTP ${res.status}` });
      continue;
    }

    const json = await res.json();
    const align = json.alignment ?? json.normalized_alignment;
    const vo = align.character_end_times_seconds.at(-1);
    const pause = pauseSeconds(align);
    const file = path.join(VO_DIR, `${id}.mp3`);
    fs.writeFileSync(file, Buffer.from(json.audio_base64, "base64"));

    beats.push({ ...b, id, vo: Number(vo.toFixed(3)),
                 pause: Number(pause.toFixed(3)) });
    console.log(
      `${String(b.n).padStart(4)}  ${b.seconds.toFixed(1)}s    ` +
      `${vo.toFixed(2)}s   ${pause.toFixed(2)}s   ${b.line.slice(0, 44)}`
    );

    logCall({ provider: "elevenlabs", model: `${MODEL}/with-timestamps`,
              unit: "characters", quantity: b.line.length, usd: 0, exact: true,
              output: file, note: `${id} — ${VOICE.name} @${VOICE.settings.speed}` });
  }

  // The picture budget is the brief's; the VO is measured. Where a beat's
  // narration overruns its budget the PICTURE gets the longer of the two, so
  // a line is never cut off by its own shot ending.
  let total = 0;
  for (const b of beats) {
    b.frames = Math.round(Math.max(b.seconds, b.vo + 0.35) * 30);
    total += b.frames;
  }

  fs.writeFileSync(OUT, JSON.stringify(
    { note: "Generated by scripts/ad-vo.mjs. Do not hand-edit.",
      fps: 30, voice: VOICE.name, beats,
      totalFrames: total,
      totalSeconds: Number((total / 30).toFixed(2)) }, null, 2) + "\n", "utf8");

  console.log(`\nfilm: ${(total / 30).toFixed(1)}s (target 60s)`);
  console.log(`written: ${OUT}`);
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((e) => { console.error(e); process.exit(1); });
}
