/**
 * Record which plates actually exist, so the film can render without them.
 *
 *   node scripts/index-plates.mjs
 *
 * The casting revision pointed beat 13 at a plate the daily Veo cap had not
 * let us generate yet, and the render died at frame 1144 with a 404. The film
 * should not be un-renderable because one shot is still queued — a beat with
 * no plate falls back to its motion version, and the cut stays watchable while
 * the picture catches up.
 *
 * Generated rather than hand-listed: a hand-kept list is a second record of
 * what is on disk, and it would be wrong exactly when a plate is added or
 * regenerated, which is the only time anybody looks.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const DIR = path.resolve(HERE, "..", "assets", "ad-broll");
const OUT = path.resolve(HERE, "..", "src", "plates.json");

function main() {
  const have = fs.existsSync(DIR)
    ? fs.readdirSync(DIR).filter((f) => f.endsWith(".mp4"))
        .map((f) => path.parse(f).name).sort()
    : [];
  fs.writeFileSync(OUT, JSON.stringify(
    { note: "Generated by scripts/index-plates.mjs. Re-run after generating " +
            "plates. A beat whose plate is absent renders its motion version.",
      have }, null, 2) + "\n", "utf8");
  console.log(`${have.length} plates: ${have.join(", ")}`);
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) main();
