/**
 * Measure each beat's audio and write src/timings.json.
 *
 *   node scripts/measure-vo.mjs
 *
 * Remotion needs every duration at build time — a composition's length cannot
 * be awaited — so the measurements are taken once, here, and committed as data.
 * The alternative is hard-coding durations, which drift the moment a line is
 * re-recorded and drift silently, because a composition that is 200ms short
 * still renders.
 *
 * GAPS ARE A DECISION, NOT A MEASUREMENT. The narration runs 66.8s and the
 * master is specced at 85–90s, so roughly twenty seconds is deliberate silence.
 * Each beat's `gapAfter` below is that decision, written down where it can be
 * argued with. They are not derived from anything.
 */
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath, pathToFileURL } from "node:url";
import { BEATS } from "../src/script.js";
import { STAGING } from "./spend-log.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const VO_DIR = path.join(STAGING, "vo");
const OUT = path.resolve(HERE, "..", "src", "timings.json");

/**
 * Seconds of silence AFTER each beat's narration, and before the first word.
 *
 * Shaped rather than spread evenly:
 *   - `lead` gives beat 1's b-roll two seconds before anyone speaks, so the
 *     film opens on an image instead of on a sentence.
 *   - the long holds are where the eye needs time on something: the pack
 *     scrolling (4), the highlighted line and its citation (5), the insights
 *     page (6), and the end card (10).
 *   - the short ones are where the line lands and should not be sat on —
 *     "Not a guess" (5) runs straight into the citation, and the price beat (8)
 *     is deliberately brisk because dwelling on a price reads as apology.
 *
 * Retuned once. The first pass budgeted against the 66.8s continuous take, but
 * that figure included the model's OWN pauses between paragraphs; the beats as
 * separate files total 59.0s of actual speech. Budgeting silence against a
 * number that already contained silence left the master 6.2s short, which is
 * exactly the kind of error a computed check catches and an eye does not.
 */
const LEAD_IN = 2.5;
const GAP_AFTER = {
  1: 1.6, 2: 2.2, 3: 1.4, 4: 3.0, 5: 2.6,
  6: 3.2, 7: 1.8, 8: 2.0, 9: 2.0, 10: 5.0,
};

function seconds(file) {
  // ffprobe writes its stream summary to STDERR, not stdout — so both are
  // captured and concatenated. Reading stdout alone found no duration and
  // threw on a file that was perfectly fine.
  const r = spawnSync("npx", ["remotion", "ffprobe", file],
                      { encoding: "utf8", shell: true });
  const out = `${r.stdout ?? ""}\n${r.stderr ?? ""}`;
  const m = out.match(/Duration:\s*(\d+):(\d+):([\d.]+)/);
  if (!m) throw new Error(`no duration found for ${file}`);
  return Number(m[1]) * 3600 + Number(m[2]) * 60 + Number(m[3]);
}

function main() {
  const beats = BEATS.map((b) => {
    const id = `beat${String(b.n).padStart(2, "0")}`;
    const file = path.join(VO_DIR, `${id}.mp3`);
    if (!fs.existsSync(file)) {
      throw new Error(`${id}.mp3 is missing — run scripts/voice-beats.mjs first`);
    }
    const vo = seconds(file);
    const gapAfter = GAP_AFTER[b.n];
    if (gapAfter === undefined) throw new Error(`no gapAfter for beat ${b.n}`);
    return { n: b.n, id, vo: Number(vo.toFixed(3)), gapAfter,
             total: Number((vo + gapAfter).toFixed(3)) };
  });

  const narration = beats.reduce((t, b) => t + b.vo, 0);
  const gaps = beats.reduce((t, b) => t + b.gapAfter, 0) + LEAD_IN;
  const master = narration + gaps;

  const data = {
    note: "Generated by scripts/measure-vo.mjs. Do not hand-edit; change " +
          "GAP_AFTER there and re-run.",
    fps: 30,
    leadIn: LEAD_IN,
    beats,
    narrationSeconds: Number(narration.toFixed(3)),
    silenceSeconds: Number(gaps.toFixed(3)),
    masterSeconds: Number(master.toFixed(3)),
  };

  fs.writeFileSync(OUT, JSON.stringify(data, null, 2) + "\n", "utf8");

  for (const b of beats) {
    console.log(
      `beat ${String(b.n).padStart(2)}  vo ${b.vo.toFixed(2).padStart(6)}s  ` +
      `+gap ${b.gapAfter.toFixed(1)}s  = ${b.total.toFixed(2).padStart(6)}s`
    );
  }
  console.log(
    `\nnarration ${narration.toFixed(1)}s + silence ${gaps.toFixed(1)}s ` +
    `= MASTER ${master.toFixed(1)}s`
  );
  console.log(
    master >= 85 && master <= 90
      ? "→ inside the 85–90s target."
      : `→ OUTSIDE the 85–90s target by ${(master < 85 ? 85 - master : master - 90).toFixed(1)}s. ` +
        "Adjust GAP_AFTER."
  );
  console.log(`\nwritten: ${OUT}`);
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) main();
